task1 = Task.create(name: "Trash", description: "Trash goes out Tuesday night.", category: "Chore")
task2 = Task.create(name: "Dishes", description: "Empty the dishwasher on monday.", category: "Chore")
task3 = Task.create(name: "Resume", description: "Update existing Resume with Flatiron info and experience.", category: "Work")
task4 = Task.create(name: "Ugh", description: "Learn Python, everyone else is doing it.", category: "Work")
task5 = Task.create(name: "null", description: "Hide the body. Maybe under neighbors porch?", category: "Muahaha")